version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202008-01
jobs:
  build:
    branches:
      only:
        - master
    executor: machine-executor
    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version

      - checkout

      - run: ./gradlew build

      - run:
          name: docker push
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            ./gradlew docker dockerPush

workflows:
  build-master:
    jobs:
      - build