name: build a branch

on:
  push:
    branches:
      - '*'
      - '!master'


jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
          java -version


      - name: run testing environment
        run: |
          cd src/test/resources
          docker-compose up &
          sleep 30s

      - name: Build
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

          export AWS_TESTING_SQS_STORAGE_REINDEX_QUEUE=${{ secrets.AWS_TESTING_SQS_QUEUE }}
          export AWS_TESTING_S3_APPLICATION_STORAGE=${{ secrets.AWS_TESTING_S3_BUCKET }}

          mvn clean install