name: build

on:
  workflow_dispatch: { }


jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
          java -version


      - name: run testing environment
        run: |
          cd src/test/resources
          docker-compose up &
          sleep 30s

      - name: Build
        run: ./gradlew build

      - name: docker push
        run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build . -t mrflick72/repository-service-k8s:latest
        docker push mrflick72/repository-service-k8s:latest
